name: on-premise-cicd
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Set Tags Name'
        required: true
        default: master

permissions:
  contents: read # 이 줄이 반드시 있어야 합니다.
  actions: write # actions: write는 워크플로 실행을 제어하는 데 사용됩니다.        

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.set-version.outputs.VERSION_NAME }}
    steps:
      - id: set-version # v1.0.0 -> v1-0-0
        run: |
          echo "VERSION_NAME=$(echo "${{ github.event.inputs.tags }}" | sed "s/\./\-/g")" >> $GITHUB_OUTPUT

      - name: Check Version Name
        run: |
          echo "Check Version -> ${{ steps.set-version.outputs.VERSOIN_NAME }}"

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.tags }}'

      - name: Grant execute permission for gradlew
        run: chmod +w gradlew

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Gradlew
        run: ./gradlew clean test bootJar

      - name: Add version
        run: |
          mv build/libs/cicd-0.0.1-SNAPSHOT.jar build/libs/cicd-${{ steps.set-version.outputs.VERSION_NAME }}.jar
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-application
          path: build/libs/cicd-${{ steps.set-version.outputs.VERSION_NAME}}.jar


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: cicd-application
          path: build/libs/

      - name: Deploy to EC2
        run:
          echo: |
            "${{ secrets.TEST_BED_PRIVATE_KEY }}" > private_key.pem
            chmod 600 private_key.pem
            scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/cicd-${{ needs.build.outputs.release }}.jar ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER_NAME }}/cicd-${{ needs.build.outputs.release }}.jar
            ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.EC2_USER_NAME }}/cicd-${{ needs.build.outputs.release }}.jar > app.log 2>&1 &"
            rm -f private_key.pem
